version: '3.9'

networks:
  rtu_mirea_vuc_schedule_default:
    external: true
  default:
    driver: bridge
services:
  postgres:
    image: postgres:15-alpine
    hostname: telegram-bot-postgres
    restart: always
    networks:
      - default
    environment:
      - POSTGRES_USER=${TELEGRAM_BOT_DB_USER}
      - POSTGRES_PASSWORD=${TELEGRAM_BOT_DB_PASSWORD}
      - POSTGRES_DB=${TELEGRAM_BOT_DB_DATABASE}
      - PGPORT=${TELEGRAM_BOT_DB_PORT}
    volumes:
      - ~/volumes/rtu_mirea_vuc_schedule_telegram_bot/postgres_data:/var/lib/postgresql/data
  pgbackups:
    image: prodrigestivill/postgres-backup-local
    hostname: telegram-bot-pgbackups
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${TELEGRAM_BOT_DB_PORT}
      - POSTGRES_DB=${TELEGRAM_BOT_DB_DATABASE}
      - POSTGRES_USER=${TELEGRAM_BOT_DB_USER}
      - POSTGRES_PASSWORD=${TELEGRAM_BOT_DB_PASSWORD}
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
    depends_on:
      - postgres
    networks:
      - default
    volumes:
      - ~/volumes/rtu_mirea_vuc_schedule_telegram_bot/pgbackups_data:/backups
  redis:
    image: bitnami/redis:latest
    hostname: telegram-bot-redis
    user: root
    restart: always
    networks:
      - default
    command: /opt/bitnami/scripts/redis/run.sh --maxclients 100000
    ports:
      - ${TELEGRAM_BOT_REDIS_PORT}
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_PORT_NUMBER: ${TELEGRAM_BOT_REDIS_PORT}
    volumes:
      - ~/volumes/rtu_mirea_vuc_schedule_telegram_bot/redis_data:/bitnami/redis/data
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: telegram-bot
    restart: always
    networks:
      - default
      - rtu_mirea_vuc_schedule_default
    env_file:
      - .env
    environment:
      TZ: Europe/Moscow
      TELEGRAM_BOT_DB_HOST: telegram-bot-postgres
      TELEGRAM_BOT_REDIS_HOST: telegram-bot-redis
      TELEGRAM_BOT_SCHEDULE_API_BASE_URL: http://schedule-service:8000
    depends_on:
      - postgres
      - redis
